# Process cores to fork the network processes
cores: 1

network:
  host: 0.0.0.0
  port: 9130

  # TLS certificate.  Set the path to accept
  # TLS connections, this MUST be set in production.
  # key: /path/to/private_key.pem
  # cert: /path/to/certificate.crt

  # This sets the session server that the game will connect to
  # to host and join their sessions.
  session_server: "127.0.0.1:9120"

  # This restricts access from certain versions of ScummVM.
  # Setting the build version by a date will disable access who have built
  # ScummVM prior to that date.  Setting it to null will restrict that version
  # all together.
  version_restrictions:
    2.8.0git: "Oct 25 2023 UTC"
